### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by formtapez**
Hello,
i added some features which were important for me.
Maybe some others will follow.
Feel free to use it :-)

This should close [Issue #10](https://github.com/fabsenet/adrilight/issues/10).

### CODE REVIEW

**Comment by fabsenet** [comment]
Thanks for your work. I am still on vacation and will get back with details after I get back home.

**Comment by fabsenet** [comment]
Hi @formtapez ,

i took some time to look at your pull request.

Some random notes:
 - 97328d1 Visual 'Studio 2017 Professional is free I see no need for backward compatibility in compiler feature usage, on the other hand, it is a single change needed only currently.
 - 868be8b **is reversing really needed? can you explain on your use case? because until today I thought, everything is possible with mirror x + mirror y + offset?**
 - I really see no point in an fps counter.
 - i really need to fix the logging issue, but limiting it via proper configuration ([see nlog.config for a start](https://github.com/fabsenet/adrilight/blob/0d7a844f635d89105c5193f4e3d2a79c7a2e1def/adrilight/NLog.config#L24))

I am grateful for your work, but it feels like a huge dump of code 💩 . 

Are you interested in collaborating on the project in a more coordinated way?

**Comment by formtapez** [comment]
Backward compatibility:
Yes, not that much change to discuss about. Btw, later i saw you did the other boolean parameters the same way. So thats not just backwards compatibility, but also an equalization to the other functions :-)

Reversing:
Yes, its needed. Initially i thought both mirrors do the same, too. But i was unable to get my LEDs working correctly. (My first LED is on bottom right, counting anti-clockwise.)

FPS:
I was just interested in it, because of this "new way" of capturing screen. Also interested how it performs with in-game capture performance with 144 Hz screen (huge FPS-changes caused by G-Sync, even on desktop etc.), and to watch the serial-timing for my limits on a further tweaked Atmel-Code actually runnning at 64 FPS with 266 LEDs... And the 3 or 4 added lines of code shouldnt be so painful to merge or resource hungry.

Coordinated way:
Interested: sure. But im not familar with Github coordination. So tell me what i did wrong, please.

Huge dump of 💩 code:
I was extra splitting my changes into single commits, so you can see code changes for every feature in a separate way. There was some big binary blob changed by visual studio, i think you can ignore that.

**Comment by fabsenet** [comment]
> And the 3 or 4 added lines of code shouldnt be so painful to merge or resource hungry.

That is true, but I want to make adrilight minimalistic and most of your changes go a different route.

It is always only some lines of code... but what do you find better?
image

or

image


Nevertheless, you did good work in your code changes, I can tell!

**Pull request closed without merging**
